"""Shared project configuration: paths, feature columns, model names."""

from __future__ import annotations

import os
from pathlib import Path

# Project root: two levels up from src/
PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"

# Canonical training input: the synthetic churn dataset produced by
# data/raw/generate_churn_data.py and versioned through the DVC `validate`
# stage. Overridable via RAW_DATA_PATH for alternative environments.
RAW_DATA_PATH = Path(os.getenv("RAW_DATA_PATH", DATA_DIR / "raw" / "dataset.csv"))

# Secondary dataset used only by the standalone fraud demo API (api/main.py,
# src/api/main.py) and its UI. Generated by data/raw/generate_creditcard_data.py.
FRAUD_DATA_PATH = Path(os.getenv("FRAUD_DATA_PATH", DATA_DIR / "raw" / "creditcard.csv"))

PROCESSED_DATA_PATH = DATA_DIR / "processed" / "dataset_clean.csv"
FEATURES_PATH = DATA_DIR / "features" / "features.parquet"
REFERENCE_DATA_PATH = DATA_DIR / "reference" / "reference.csv"
MODELS_DIR = PROJECT_ROOT / "models"
REPORTS_DIR = PROJECT_ROOT / "reports"
MONITORING_REPORTS_DIR = PROJECT_ROOT / "monitoring" / "reports"
MODEL_CARDS_DIR = PROJECT_ROOT / "model_cards"
MLFLOW_DIR = PROJECT_ROOT / "mlflow" / "mlruns"

# Target / sensitive attribute / id
TARGET_COL = "churn"
SENSITIVE_COL = "gender"
ID_COL = "customer_id"
TIMESTAMP_COL = "timestamp"

NUMERIC_FEATURES = [
    "age",
    "tenure_months",
    "monthly_charges",
    "total_charges",
    "num_services",
    "support_tickets",
    "avg_call_minutes",
]

BINARY_FEATURES = [
    "has_online_backup",
    "has_device_protection",
    "has_tech_support",
]

CATEGORICAL_FEATURES = [
    "region",
    "contract_type",
    "payment_method",
]

# Full feature set fed to the model
BASE_FEATURES = NUMERIC_FEATURES + BINARY_FEATURES + CATEGORICAL_FEATURES

# Plausible ranges enforced by clamp_numeric during preprocessing.
NUMERIC_RANGES = {
    "age": (18, 100),
    "tenure_months": (0, 120),
    "monthly_charges": (0, 500),
    "total_charges": (0, 60000),
    "num_services": (0, 10),
    "support_tickets": (0, 50),
    "avg_call_minutes": (0, 5000),
}

# Fairness / drift metrics thresholds
FAIRNESS_DP_THRESHOLD = 0.1
DRIFT_THRESHOLD = 0.3
F1_PROMOTION_THRESHOLD = 0.25
AUC_PROMOTION_THRESHOLD = 0.80
CHALLENGER_RATIO = 0.1
